# kotlin or fml
modLoader="javafml"

loaderVersion="[${loaderInterval},)"

license="${license_type}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="${issues_url}"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
   modId="nucleoplasm" #mandatory
   version="${version}" #mandatory
   displayName="nucleoplasm" #mandatory
   displayURL="https://github.com/xenfork"
   logoFile="icon.png"
   authors="${authors}" #optional
   description='''

   '''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.nucleoplasm]] #optional
   # the modid of the dependency
   modId="forge" #mandatory
   # Does this dependency have to exist - if not, ordering below must be specified
   mandatory=true #mandatory
   # The version range of the dependency
   versionRange="[${loaderInterval},)" #mandatory
   # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
   ordering="NONE"
   # Side this dependency is applied on - BOTH, CLIENT or SERVER
   side="BOTH"
# Here's another dependency
[[dependencies.nucleoplasm]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="[${minecraft_version},${alpha_minecraft_version})"
   ordering="NONE"
   side="BOTH"
